apps/appointments_app/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', index, name = 'home'),
    url(r'^add_appt$', add_appt, name = 'add_appt'),
    url(r'^(?P<id>\d+)/edit$', edit_appt, name = 'edit_appt'),
    url(r'^(?P<id>\d+)/update$', update_appt, name = 'update_appt'),
    url(r'^(?P<id>\d+)/destroy$', remove_appt, name = 'remove_appt'),
]

apps/login_app/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', index, name = 'index'),
    url(r'^register$', register, name = 'register'),
    url(r'^login$', login, name = 'login'),
    url(r'^logout$', logout, name = 'logout'),
]

belt_exam/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.login_app.urls', namespace="login")),
    url(r'^appointments/', include('apps.appointments_app.urls', namespace = 'appointments')),
]

apps/appointments_app/models.py
from __future__ import unicode_literals
import datetime
from django.db import models
from ..login_app.models import User

# Create your models here.
class AppointmentManager(models.Manager):
    def add_appointment(self, task, date, time, user_id):
        user = User.objects.get(id = user_id)
        Appointment.objects.create(task = task, date = date, time = time, user = user)
        return True

    def validate_appt(self, user_id, date = None, time = None, id = None):
        errors = []
        print time, "is time 1"
        print date, "is date 2"
        if date < datetime.date.today().isoformat():
            errors.append("Appointments cannot be for the past!")
        if date == datetime.date.today().isoformat():
            if time < datetime.datetime.now().time().isoformat():
                errors.append("Appointments cannot be for the past!")
        if Appointment.objects.filter(user__id = user_id).filter(date = date).filter(time = time).exclude(id = id):
            errors.append('You can not schedule two appointments at the same time.')
        return errors

class Appointment(models.Model):
    task = models.CharField(max_length=50)
    status = models.CharField(max_length=10, default="pending")
    time = models.TimeField()
    date = models.DateField()
    user = models.ForeignKey(User, related_name = "user_appointment")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = AppointmentManager()

apps/appointments_app/views.py
from django.shortcuts import render, redirect
import datetime
from .models import *
from django.contrib import messages


def index(request):
    if 'id' not in request.session:
        return redirect('login:index')
    user_id = request.session['id']
    today = datetime.datetime.now().date()
    current_time = datetime.datetime.now().time()
    appointments_today = Appointment.objects.filter(user = user_id).filter(date = today).exclude(time__lt= current_time).order_by('time')
    other_appointments = []
    for a in appointments_today:
        other_appointments = Appointment.objects.filter(user = user_id).exclude(date__lte= today).order_by('date', 'time')
    context = {'today': today,
               'appointments_today': appointments_today,
               'other_appointments': other_appointments
               }
    return render(request, 'appointments_app/home.html', context)

def add_appt(request):
    if request.method == 'POST':
        date = request.POST['date']
        time = request.POST['time']
        task = request.POST['task']
        user_id = request.session['id']
        errors = []
        errors += Appointment.objects.validate_appt(user_id, date, time)
        if errors:
            for error in errors:
                messages.error(request, error)
        else:
            Appointment.objects.add_appointment(task, date, time, user_id)
    return redirect('appointments:home')

def edit_appt(request, id):
    if 'id' not in request.session:
        return redirect('login:index')
    appointment = Appointment.objects.get(id = id)
    appointment_time = str(appointment.time)
    appointment_date = str(appointment.date)
    context = {
        'appointment': appointment,
        'appointment_date': appointment_date,
        'appointment_time': appointment_time
        }
    return render(request, 'appointments_app/edit.html', context)

def update_appt(request, id):
    if 'id' not in request.session:
        return redirect('login:index')
    user_id = request.session['id']
    if request.method == 'POST':
        errors = []
        task = request.POST['task']
        status = request.POST['status']
        user_id = request.session['id']
        time = request.POST['time']
        date = request.POST['date']
        errors += Appointment.objects.validate_appt(user_id, date, time, id)
        if errors:
            for error in errors:
                messages.error(request, error)
                return redirect('appointments:edit_appt', id = id)
        else:
            Appointment.objects.filter(id = id).update(status = status, task= task, time = time, date = date)
    return redirect('appointments:home')

def remove_appt(request, id):
        Appointment.objects.filter(id=id).delete()
        return redirect('appointments:home')

apps/appointments_app/templates/appointments_app/edit.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  {% load staticfiles %}
  <link rel="stylesheet" href="{% static 'appointments_app/bootstrap.min.css' %}">
  <title>Update Appointment</title>
</head>
<body>
  <div class="container">
    <div class="row col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
      </div>
      <div class="text-right col-lg-6 col-md-6 col-sm-6 col-xs-6">
        <div>&nbsp;</div>
        <a href="{% url 'appointments:home' %}">Dashboard</a>&nbsp;&nbsp;<a href="{% url 'login:logout' %}">Logout</a>
      </div>
    </div><!-- end header -->
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <h4>Update {{ appointment.task }} </h4>
      <div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
        <form class="form-horizontal" action="{% url 'appointments:update_appt' id=appointment.id %}" method="POST">
          {% csrf_token %}
          <fieldset>
          <div class="control-group">
            <label class="control-label" for="review">Task</label>
            <div class="controls">
              <input type="text" name="task" class="input-xlarge" value ="{{ appointment.task }}">
            </div>
          </div>
          <div class="control-group">
            <label class="control-label" for="status">Status</label>
            <select name="status">
              <option {% if appointment.status == "pending" %} selected {% endif %} value="pending">Pending</option>
              <option {% if appointment.status == "missed" %} selected {% endif %} value="missed">Missed</option>
              <option {% if appointment.status == "done" %} selected {% endif %} value="done">Done</option>
            </select>
          </div>
          <div class="control-group">
            <label class="control-label" for="Date">Date:</label>
              <input type="date" name="date" class="input-xlarge" value ="{{ appointment_date }}">
              <h6>Current appointment date is {{ appointment.date }}</h6>
          </div>
          <div class="control-group">
            <label class="control-label" for="time">Time:</label>
            <input type="time" name="time" class="input-xlarge" value="{{ appointment_time }}">
            <h6>Current appointment time is {{ appointment.time }}</h6>
          </div>
          <input type="submit" value="Update">
          </fieldset>
        </form>
        {% if messages %}
          {% for message in messages %}
            <p {% if message.tags %} class="text-danger"{% endif %}>{{message}}</li>
          {% endfor %}
        {% endif %}
      </div>
    </div>
  </div>
</body>
</html>

apps/appointments_app/templates/appointments_app/home.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  {% load staticfiles %}
  <link rel="stylesheet" href="{% static 'appointments_app/bootstrap.min.css' %}">
  <title>What's Up</title>
</head>
<body>
  <div class="container">
    <div class="row col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
        <h2>Hello, {{ request.session.first_name }}</h2>
      </div>
      <div class="text-right col-lg-6 col-md-6 col-sm-6 col-xs-6">
        <div>&nbsp;</div>
        <a href="{% url 'login:logout' %}">Logout</a>
      </div>
    </div><!-- end well -->
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <h3>Here are your appointments for today, {{ today }}: </h3>
      {% if appointments_today %}
        <table class="table table-striped">
          <thead>
            <th>Tasks</th>
            <th>Time</th>
            <th>Status</th>
            <th>Actions</th>
          </thead>
          <tbody>
              {% for appointment in appointments_today %}
                <tr>
                  <td>{{ appointment.task }}</td>
                  <td>{{ appointment.time }}</td>
                  <td>{{ appointment.status }}</td>
                  <td>{% if appointment.status != "done" %}
                        <a href="{% url 'appointments:edit_appt' id=appointment.id %}">Edit</a><span>&nbsp;</span><span>&nbsp;</span>
                      {% endif %}
                    <a href="{% url 'appointments:remove_appt' id=appointment.id %}">Remove</a></td>
                </tr>
              {% endfor %}
          </tbody>
        </table>
      {% endif %}
      {% if not appointments_today %}
        <p>&nbsp;</p>
        <div>
          <h4 class="text-center text-danger">No Appointments Today.</h4>
        </div>
      {% endif %}
    </div>
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <h3>Your future appointments:</h3>
      <table class="table table-striped">
        <thead>
          <th>Tasks</th>
          <th>Date</th>
          <th>Time</th>
        </thead>
        <tbody>
          {% if other_appointments %}
            {% for appointment in other_appointments %}
              <tr>
                <td>{{ appointment.task }}</td>
                <td>{{ appointment.date }}</td>
                <td>{{ appointment.time }}</td>
              </tr>
            {% endfor %}
          {% endif %}
        </tbody>
    </table>
    <p>&nbsp;</p>
    </div>
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <h4>Add Appointment</h4>
      <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
        <form class="form-horizontal" action="{% url 'appointments:add_appt' %}" method="POST">
          {% csrf_token %}
          <div class="control-group">
            <label class="control-label" for="Date">Date:</label>
              <input type="date" name="date" value="">
          </div>
          <div class="control-group">
            <label class="control-label" for="time">Time:</label>
            <input type="time" name="time">
          </div>
          <div class="control-group">
            <label for="review">Tasks:</label>
              <input type="text" name="task" value="">
          </div>
          <div class="text-right">
            <p>&nbsp;</p>
            <input type="submit" value="Add">
          </div>
        </form>
      </div>
      <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
        {% if messages %}
          {% for msg in messages %}
          <div class="alert-message block-message error">
            <p class="text-danger">{{ msg }}</p>
          </div>
          {% endfor %}
        {% endif %}
      </div>
    </div>
  </div>
</body>
</html>